apiVersion: apps/v1
kind: Deployment
metadata:
  name: env0-nfs-server
  namespace: env0-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      role: env0-nfs-server
  template:
    metadata:
      labels:
        role: env0-nfs-server
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-central1-a
      containers:
      - name: nfs-server
        image: ghcr.io/kubernetes-sigs/nfs-ganesha:v3.5
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /data
            name: nfs-pvc
        resources:
          limits:
            cpu: 250m
            memory: 1000Mi
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: env0-pvc-for-nfs-server         
