apiVersion: v1
kind: PersistentVolume
metadata:
  name: env0-pv-for-nfs-server
spec:
  storageClassName: env0-sc-for-nfs-server
  capacity:
    storage: 300Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: env0-internal-state-disk
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-central1-a
          - us-central1-b
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-central1-a
          - us-central1-b
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-central1
