apiVersion: v1
kind: PersistentVolume
metadata:
  name: env0-nfs-pv
spec:
  storageClassName: env0-state-sc
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: env0-nfs-server.env0-agent.svc.cluster.local
    path: "/"
